/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_modelstaging_free: (a: number, b: number) => void;
export const __wbg_wasmengine_free: (a: number, b: number) => void;
export const bench_frame_kernels: (a: number) => [number, number];
export const bench_int8_gemv: (a: number, b: number, c: number, d: number, e: number) => [number, number, number];
export const int8_route: () => [number, number];
export const modelstaging_filled: (a: number) => number;
export const modelstaging_finish_artifact: (a: number) => [number, number];
export const modelstaging_finish_codec: (a: number) => [number, number];
export const modelstaging_new: () => number;
export const modelstaging_push_codec_tensor: (a: number, b: number, c: number, d: number, e: number) => [number, number];
export const modelstaging_push_fttsq: (a: number, b: number, c: number) => [number, number];
export const modelstaging_reserve_fttsq: (a: number, b: number) => [number, number];
export const modelstaging_reserve_fttsq_hot_prefix: (a: number, b: number, c: bigint) => [number, number];
export const preset_vector: (a: number, b: number) => [number, number, number, number];
export const presets: () => [number, number];
export const wasmengine_enroll: (a: number, b: number, c: number) => [number, number, number, number];
export const wasmengine_enroll_raw: (a: number, b: number, c: number) => [number, number, number, number];
export const wasmengine_from_staging: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number, number];
export const wasmengine_new: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number) => [number, number, number];
export const wasmengine_synthesize: (a: number, b: number, c: number, d: number, e: number, f: bigint, g: number) => [number, number, number, number];
export const wasmengine_synthesize_with_text_rows: (a: number, b: number, c: number, d: number, e: number, f: bigint, g: number, h: number, i: number, j: number) => [number, number, number, number];
export const wasmengine_text_row_ids: (a: number, b: number, c: number) => [number, number, number, number];
export const worker_loop_entry: (a: number) => [number, number];
export const worker_team_width: () => number;
export const arm_worker_team: (a: number) => void;
export const install_panic_hook: () => void;
export const publish_team_block: () => void;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
