[package]
name = "ftts-model-qwen"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
fancy-regex = "0.18"
ftts-artifacts = { path = "../ftts-artifacts" }
ftts-core = { path = "../ftts-core" }
ftts-kernels = { path = "../ftts-kernels" }
rustfft = "6.2"
serde_json = "1.0"
unicode-normalization = "0.1"

[lints]
workspace = true
